version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on host to port 80 on container
    volumes:
      - .:/var/www/html  # Mount local directory to container's working directory
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public  # Set Apache document root to Laravel's public folder
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
